---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# The Python Programming Language: Functions

In [0]:
x = 1
y = 2
x + y

In [0]:
x

<br>
`add_numbers` is a function that takes two numbers and adds them together.

In [0]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

<br>
`add_numbers` updated to take an optional 3rd parameter. Using `print` allows printing of multiple expressions within a single cell.

In [0]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

<br>
`add_numbers` updated to take an optional flag parameter.

In [0]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

<br>
Assign function `add_numbers` to variable `a`.

In [0]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

<br>
# The Python Programming Language: Types and Sequences

<br>
Use `type` to return the object's type.

In [0]:
type('This is a string')

In [0]:
type(None)

In [0]:
type(1)

In [0]:
type(1.0)

In [0]:
type(add_numbers)

<br>
Tuples are an immutable data structure (cannot be altered).

In [0]:
x = (1, 'a', 2, 'b')
type(x)

<br>
Lists are a mutable data structure.

In [0]:
x = [1, 'a', 2, 'b']
type(x)

<br>
Use `append` to append an object to a list.

In [0]:
x.append(3.3)
print(x)

<br>
This is an example of how to loop through each item in the list.

In [0]:
for item in x:
    print(item)

<br>
Or using the indexing operator:

In [0]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

<br>
Use `+` to concatenate lists.

In [0]:
[1,2] + [3,4]

<br>
Use `*` to repeat lists.

In [0]:
[1]*3

<br>
Use the `in` operator to check if something is inside a list.

In [0]:
1 in [1, 2, 3]

<br>
Now let's look at strings. Use bracket notation to slice a string.

In [0]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters


<br>
This will return the last element of the string.

In [0]:
x[-1]

<br>
This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [0]:
x[-4:-2]

<br>
This is a slice from the beginning of the string and stopping before the 3rd element.

In [0]:
x[:3]

<br>
And this is a slice starting from the 3rd element of the string and going all the way to the end.

In [0]:
x[3:]

In [0]:
firstname = 'John'
lastname = 'Doe'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)

John Doe
JohnJohnJohn
False


<br>
`split` returns a list of all the words in a string, or a list split on a specific character.

In [0]:
firstname = 'John Doe'.split(' ')[0] # [0] selects the first element of the list
lastname = 'John Doe'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

<br>
Make sure you convert objects to strings before concatenating.

In [0]:
'Chris' + 2

TypeError: ignored

In [0]:
'Chris' + str(2)

<br>
Dictionaries associate keys with values.

In [0]:
x = {'John Doe': 'johndoe@gmail.com', 'Bill Gates': 'billg@microsoft.com'}
x['John Doe'] # Retrieve a value by using the indexing operator


'johndoe@gmail.com'

In [0]:
x['Jeff Bezos'] = None
x['Jeff Bezos']

<br>
Iterate over all of the keys:

In [0]:
for name in x:
    print(x[name])

johndoe@gmail.com
billg@microsoft.com
None


<br>
Iterate over all of the values:

In [0]:
for email in x.values():
    print(email)

johndoe@gmail.com
billg@microsoft.com
None


<br>
Iterate over all of the items in the list:

In [0]:
for name, email in x.items():
    print(name)
    print(email)

John Doe
johndoe@gmail.com
Bill Gates
billg@microsoft.com
Jeff Bezos
None


<br>
You can unpack a sequence into different variables:

In [0]:
x = ('John', 'Doe', 'johndoe@gmail.com')
print(type(x))
fname, lname, email = x

<class 'tuple'>


In [0]:
fname

'John'

In [0]:
lname

<br>
Make sure the number of values you are unpacking matches the number of variables being assigned.

In [0]:
x = ('John', 'Doe', 'johndoe@gmail.com', 'USA')
fname, lname, email = x

<br>
# The Python Programming Language: More on Strings

In [0]:
print('John' + 2)

In [0]:
print('John' + str(2))

<br>
Python has a built in method for convenient string formatting.

In [0]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'John'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


<br>
# The Python Programming Language: Objects and map()

<br>
An example of a class in python:

In [0]:
class Person:
    department = 'Computer Engineering' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [0]:
person = Person()
person.set_name('John Doe')
person.set_location('New York City, NY, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

<br>
Here's an example of mapping the `min` function between two lists.

In [0]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

<br>
Now let's iterate through the map object to see the values.

In [0]:
for item in cheapest:
    print(item)

<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [0]:
my_function = lambda a, b, c : a + b

In [0]:
my_function(1, 2, 3)

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [0]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

<br>
Now the same thing but with list comprehension.

In [0]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [0]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [0]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [0]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [0]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [0]:
m.shape

(2, 3)

<br>
`arange` returns evenly spaced values within a given interval.

In [0]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [0]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [0]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

<br>
`resize` changes the shape and size of array in-place.

In [0]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [0]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [0]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [0]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

<br>
Create an array using repeating list (or see `np.tile`)

In [0]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [0]:
np.tile(np.array([1, 2, 3]), 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [0]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
#### Combining Arrays

In [0]:
p = np.ones((2, 3), int)
p

array([[1, 1, 1],
       [1, 1, 1]])

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [0]:
np.vstack((p, 2*p))

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [0]:
np.hstack((p, 2*p))

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [0]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [0]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [0]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [0]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [0]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [0]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>
The shape of array `z` is `(2,3)` before transposing.

In [0]:
z.shape

(2, 3)

<br>
Use `.T` to get the transpose.

In [0]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [0]:
z.T.shape

(3, 2)

<br>
Use `.dtype` to see the data type of the elements in the array.

In [0]:
z.dtype

dtype('int64')

<br>
Use `.astype` to cast to a specific type.

In [0]:
z = z.astype('f')
z.dtype

dtype('float32')

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [0]:
a = np.array([-4, -2, 1, 3, 5])

In [0]:
a.sum()

3

In [0]:
a.max()

5

In [0]:
a.min()

-4

In [0]:
a.mean()

0.6

In [0]:
a.std()

3.2619012860600183

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [0]:
a.argmax()

4

In [0]:
a.argmin()

0

<br>
## Indexing / Slicing

In [0]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [0]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [0]:
s[1:5]

<br>
Use negatives to count from the back.

In [0]:
s[-4:]

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [0]:
s[-5::-2]

<br>
Let's look at a multidimensional array.

In [0]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Use bracket notation to slice: `array[row, column]`

In [0]:
r[2, 2]

14

<br>
And use : to select a range of rows or columns

In [0]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [0]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [0]:
r[-1, ::2]

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [0]:
r[r > 30]

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [0]:
r[r > 30] = 30
r

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [0]:
r2 = r[:3,:3]
r2

<br>
Set this slice's values to zero ([:] selects the entire array)

In [0]:
r2[:] = 0
r2

<br>
`r` has also been changed!

In [0]:
r

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [0]:
r_copy = r.copy()
r_copy

<br>
Now when r_copy is modified, r will not be changed.

In [0]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [0]:
test = np.random.randint(0, 10, (4,3))
test

<br>
Iterate by row:

In [0]:
for row in test:
    print(row)

<br>
Iterate by index:

In [0]:
for i in range(len(test)):
    print(test[i])

<br>
Iterate by row and index:

In [0]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

<br>
Use `zip` to iterate over multiple iterables.

In [0]:
test2 = test**2
test2

In [0]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)